ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS lat FLOAT8,
  ADD COLUMN IF NOT EXISTS lng FLOAT8,
  ADD COLUMN IF NOT EXISTS postcode_district TEXT GENERATED ALWAYS AS (
    UPPER(SPLIT_PART(TRIM(postcode), ' ', 1))
  ) STORED;
